[project]
name = "hzk-pixel-font"
version = "0.0.0"
requires-python = ">=3.14"

dependencies = [
    "pixel-font-builder==0.0.47",
    "pixel-font-knife==0.0.21",
    "character-encoding-utils==0.0.12",
    "pillow==12.1.1",
    "loguru==0.7.3",
]
